{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "06d988b7_4c1d4d03",
        "filename": "src/test/java/com/googlesource/gerrit/plugins/replication/pull/api/ProjectInitializationActionIT.java",
        "patchSetId": 8
      },
      "lineNbr": 90,
      "author": {
        "id": 1083454
      },
      "writtenOn": "2021-11-03T13:42:36Z",
      "side": 1,
      "message": "Why for replica we have INTERNAL_ERROR and for primary BAD_REQUEST?",
      "range": {
        "startLine": 90,
        "startChar": 55,
        "endLine": 90,
        "endChar": 79
      },
      "revId": "d5238a4c00467ee7a8b19d236c78c26276b1c65a",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}